[package]
name = "pub"
version = "0.0.1"
edition = "2021"
description = "publish dir content to the open internet"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "main.rs"

[[bin]]
name = "static"
path = "static.rs"

[dependencies]
libc = "0.2"
