[package]
name = "pub"
version = "0.1.2"
edition = "2021"
description = "publish dir, port, url to the open web"
license = "MIT"
include = ["*.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pub"
path = "main.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tar = "0.4"
xz2 = "0.1"
